packages:
  - "apps/*"
  - "packages/*"

engineStrict: true
preferWorkspacePackages: true
autoInstallPeers: true
strictPeerDependencies: false

allowBuilds:
  "@nestjs/core": true
  "unrs-resolver": true
